config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations:"registrations",sessions: :sessions }

  root "top#index"

  resources :posts, only: %i(new create index show destroy) do
    resources :arts, only: %i(create)
    resources :comments, only: %i(create destroy)
    collection do
      get 'search'
    end
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
   end

  resources :users, only:[:show,:index]
  resources :reactions, only: [:create]
  resources :matching, only: [:index]

  resources :chat_rooms, only: [:create, :show]

  get "/swipe", to: "posts#swipe"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  belongs_to :post

  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users
  has_many :chat_messages
  has_many :users, through: :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :arts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reactions, -> { order(created_at: :desc) }, dependent: :destroy

  accepts_nested_attributes_for :arts
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  has_many :chat_room_users, dependent: :destroy
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages, dependent: :destroy

  has_one :card, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,presence: true
  validates :self_introduction,length: { maximum: 500 }

  mount_uploader :profile_image, ProfileImageUploader

  def update_without_current_password(params, *options)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user

  def index
    @users = User.where.not(id: current_user.id)
  end

  def show
    # URLのuserを取得
    @user = User.find(params[:id])
    # URLのuserのポストを取得
    @posts = Post.where(user_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(name, **options)
    Initials.svg(name, size: 40)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="overflow-x-auto w-full">
  <table class="table w-full">
    <!-- head -->
    <thead>
      <tr>
        <th>名前</th>
        <th>プロフィール</th>
        <th>ダイレクトメッセージ</th>
      </tr>
    </thead>
    <tbody>
      <!-- ユーザー情報 -->
      <% @users.each do |user| %>
        <tr>
          <td>
            <div class="flex items-center space-x-3">
              <% if user.profile_image.url.nil? %>
                <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                  <div class="w-10 rounded-full">
                    <%= user_avatar(user.name) %>
                  </div>
                </label>
              <% else %>
                <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                  < class="w-10 rounded-full">
                    <%= image_tag user.profile_image.url, class: "profile-img" %>
                  </div>
                </label>
              <% end %>
              <div class="font-bold">
                <%= user.name %>
                <%= button_to "詳細ページへ", user_path(id: user.id), method: :get, class: "btn btn-primary" %>
              </div>
            </div>
          </td>
          <td>
            <%= user.self_introduction %>
          </td>
          <td>
            <%= button_to "メッセージを送る", chat_rooms_path(params: { user_id: user.id }), method: :post, class: "btn btn-secondary"  %>
          </td>
        </tr>
      <% end %>
  </table>
</div>

app/views/users/show.html.erb
<div class="hero min-h-screen bg-base-200">
  <div class="hero-content flex-col lg:flex-row">
    <%# avatar %>
    <% if @user.profile_image.url.nil? %>
      <%= user_avatar(@user.name) %>
    <% else %>
      <%= image_tag @user.profile_image.url, class: "profile-img" %>
    <% end %>
    <div>
      <%# username %>
      <div class="text-5xl font-bold">
        <%= @user.name %>
      </div>
      <p class="py-6">
        <%= @user.self_introduction %>
      </p>
      <% if @user == current_user %>
        <%# edit_link %>
        <%= button_to "編集", edit_user_registration_path, method:"get", class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>
<h1 class="font-bold text-center text-3xl">作字一覧</h1>
<div class="grid grid-cols-1 md:grid-cols-3 mt-5">
  <% @posts.each do |post| %>
    <%# 投稿表示 %>
    <div class="card w-96 bg-base-100 shadow-xl">
      <%# 投稿画像 %>
      <%= link_to(post_path(post)) do %>
        <%= image_tag post.arts.first.image.url(:medium) %>
      <% end %>
      <%# 投稿情報 %>
      <div class="card-body">
        <%# 作品詳細 %>
        <%= post.art_text %>
        <div class="justify-end card-actions">

        </div>

      </div>
    </div>
  <% end %>
</div>