config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations:"registrations",sessions: :sessions }

  root "top#index"

  resources :posts, only: %i(new create index show destroy) do
    resources :arts, only: %i(create)
    resources :comments, only: %i(create destroy)
    collection do
      get 'search'
    end
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
   end

  resources :users, only:[:show,:index]
  resources :reactions, only: [:create]
  resources :matching, only: [:index]

  resources :chat_rooms, only: [:create, :show]

  get "/swipe", to: "posts#swipe"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  belongs_to :post

  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users
  has_many :chat_messages
  has_many :users, through: :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :arts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reactions, -> { order(created_at: :desc) }, dependent: :destroy

  accepts_nested_attributes_for :arts
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  has_many :chat_room_users, dependent: :destroy
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages, dependent: :destroy

  has_one :card, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,presence: true
  validates :self_introduction,length: { maximum: 500 }

  mount_uploader :profile_image, ProfileImageUploader

  def update_without_current_password(params, *options)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="cyberpunk">
  <head>
    <title>Sakujiru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://js.pay.jp/v2/pay.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'tailwind', media: 'all', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>
  </head>

  <body class="flex flex-col min-h-screen">
    <% unless current_page?(root_path) || current_page?("/users/sign_in") || current_page?("/users/sign_up") %>
    <%# header %>
    <header class="flex-grow">
      <%= render "partial/header" %>
    </header>
    <% end %>
    <main class="flex-grow">
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
    </main>
    <%# footer %>
    <footer>
      <%= render "partial/footer" %>
    </footer>
  </body>
</html>

app/views/partial/*_header.html.erb
<%# header %>
<div class="navbar shadow-lg bg-neutral text-neutral-content rounded-box">
  <%# タイトル ヘッダー左 %>
  <div class="flex-1 px-2 mx-2">
    <%# POSTS LINK %>
    <%= link_to "Sakujiru", posts_path, class: "text-lg font-bold" %>
  </div>
  <%# ナビゲーション ヘッダー右 %>
  <div class="flex-none hidden px-2 mx-2 lg:flex">
    <%# ナビゲーション ヘッダー右 %>
    <div class="flex items-stretch">
      <%# ログイン後 %>
      <% if current_user %>
        <%# swipe %>
        <%= link_to "マッチング", swipe_path, class: "btn btn-ghost btn-sm rounded-btn" %>
        <%# 作字一覧 %>
        <%= link_to "作字一覧", posts_path, class: "btn btn-ghost btn-sm rounded-btn"%>
        <%# 新規投稿 %>
        <%= link_to "新規投稿", new_post_path, class: "btn btn-ghost btn-sm rounded-btn" %>
        <%# マイページ %>
        <%= link_to "マイページ", user_path(current_user), class: "btn btn-ghost btn-sm rounded-btn" %>
        <%# Log out %>
        <%= button_to "サインアウト", destroy_user_session_path, method: :delete, class: "btn btn-ghost btn-sm rounded-btn" %>
      <%# ログイン前 %>
      <% else %>
        <%# 作字一覧 %>
        <%= link_to "作字一覧", posts_path, class: "btn btn-ghost btn-sm rounded-btn"%>
        <%# SING UP %>
        <%= link_to "新規登録", new_user_registration_path, class: "btn btn-ghost btn-sm rounded-btn" %>
        <%# LOG IN %>
        <%= link_to "ログイン", new_user_session_path, class: "btn btn-ghost btn-sm rounded-btn" %>
      <% end %>
    </div>
  </div>

  <%# ハンバーガー ヘッダー右 %>
  <div class="flex-none">
    <button class="btn btn-square btn-ghost">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
      </svg>
    </button>
  </div>

</div>

app/views/partial/_footer.html.erb
<footer class="p-10 footer bg-neutral text-neutral-content">
  <div>
    <svg width="50" height="50" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" class="fill-current"><path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path></svg>
    <p>@Sakujiru</p>
  </div> 
  <div>
    <span class="footer-title">Social</span> 
    <div class="grid grid-flow-col gap-4">
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a> 
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path></svg></a> 
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path></svg></a>
    </div>
  </div>
</footer>

app/views/partial/_header.html.erb
<div class="navbar bg-base-100">
  <%# navbar 左　タイトルロゴ　%>
  <div class="flex-1">
    <%# POSTS LINK %>
    <%= link_to "Sakujiru", root_path, class: "text-lg font-bold" %>
  </div>
  <%# navbar　右　%>
  <div class="flex-none gap-2">
    <%# ドロップダウン %>
    <div class="dropdown dropdown-end">
      <% if @set_current_user %>
        <%# avatar %>
        <% if @set_current_user.profile_image.url.nil? %>
          <label tabindex="0" class="btn btn-ghost btn-circle avatar">
            <div class="w-10 rounded-full">
              <%= user_avatar(@set_current_user.name) %>
            </div>
          </label>
        <% else %>
          <label tabindex="0" class="btn btn-ghost btn-circle avatar">
            <div class="w-10 rounded-full">
              <%= image_tag @set_currrent_user.profile_image.url, class: "profile-img" %>
            </div>
          </label>
        <% end %>
      <% else %>
        <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <img src="https://api.lorem.space/image/face?hash=33791">
          </div>
        </label>
      <% end %>
      <%# ドロップダウン　項目　%>
      <ul tabindex="0" class="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-52">
        <%# ログイン後 %>
        <% if current_user %>
          <%# swipe %>
          <li><%= link_to "マッチング", swipe_path, class: "btn btn-ghost btn-sm rounded-btn" %></li>
          <%# いいねした投稿　%>
          <li><%= link_to "いいね一覧", matching_index_path, class: "btn btn-ghost btn-sm rounded-btn"%></li>
          <%# 作字一覧 %>
          <li><%= link_to "作字一覧", posts_path, class: "btn btn-ghost btn-sm rounded-btn"%></li>
          <%# 新規投稿 %>
          <li><%= link_to "新規投稿", new_post_path, class: "btn btn-ghost btn-sm rounded-btn" %></li>
          <%# ユーザー一覧 %>
          <li><%= link_to "クリエイター一覧", users_path, class: "btn btn-ghost btn-sm rounded-btn" %></li>
          <%# マイページ %>
          <li><%= link_to "マイページ", user_path(current_user), class: "btn btn-ghost btn-sm rounded-btn" %></li>
          <%# クレジットカード登録　%>
          <li><%= link_to "クレジットカード", card_path(current_user), class: "btn btn-ghost btn-sm rounded-btn" %></li>
          <%# Log out %>
          <li><%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "btn btn-ghost btn-sm rounded-btn" %></li>
        <%# ログイン前 %>
        <% else %>
          <%# 作字一覧 %>
          <li><%= link_to "作字一覧", posts_path, class: "btn btn-ghost btn-sm rounded-btn"%></li>
          <%# SING UP %>
          <li><%= link_to "新規登録", new_user_registration_path, class: "btn btn-ghost btn-sm rounded-btn" %></li>
          <%# LOG IN %>
          <li><%= link_to "ログイン", new_user_session_path, class: "btn btn-ghost btn-sm rounded-btn" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>