config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations:"registrations",sessions: :sessions }

  root "top#index"

  resources :posts, only: %i(new create index show destroy) do
    resources :arts, only: %i(create)
    resources :comments, only: %i(create destroy)
    collection do
      get 'search'
    end
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
   end

  resources :users, only:[:show,:index]
  resources :reactions, only: [:create]
  resources :matching, only: [:index]

  resources :chat_rooms, only: [:create, :show]

  get "/swipe", to: "posts#swipe"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  belongs_to :post

  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users
  has_many :chat_messages
  has_many :users, through: :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :arts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reactions, -> { order(created_at: :desc) }, dependent: :destroy

  accepts_nested_attributes_for :arts
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  has_many :chat_room_users, dependent: :destroy
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages, dependent: :destroy

  has_one :card, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,presence: true
  validates :self_introduction,length: { maximum: 500 }

  mount_uploader :profile_image, ProfileImageUploader

  def update_without_current_password(params, *options)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user

  require 'payjp'

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    if params['payjp_token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト',
      email: current_user.email,
      card: params['payjp_token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(
        user_id: current_user.id,
        customer_id: customer.id,
        card_id: customer.default_card
      )
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def show
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def delete
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
    redirect_to action: "new"
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(name, **options)
    Initials.svg(name, size: 40)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/new.html.erb
<div class="flex justify-center">
  <div class="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
    <div class="card-body">

      <%# カード番号 %>
      <div class="form-control">
        <div id="number-form" class="payjs-outer input input-bordered"><!-- ここにカード番号入力フォームが生成されます --></div>
      </div>

      <%# 有効期限 %>
      <div class="form-control">
        <div id="expiry-form" class="payjs-outer input input-bordered"><!-- ここに有効期限入力フォームが生成されます --></div>
      </div>

      <%# CVC %>
      <div class="form-control">
        <div id="cvc-form" class="payjs-outer input input-bordered"><!-- ここにCVC入力フォームが生成されます --></div>
      </div>

      <%# 登録ボタン %>
      <%= form_with url: pay_cards_path, method: :post, id: "card_form" do |f| %>
        <div id="card_token"></div>
        <%= f.submit "登録する", class:"btn", id: "info_submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cards/show.html.erb
<div class="flex justify-center">
  <div class="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
    <div class="card-body">

      <%# カード番号 %>
      <div>
        カード番号
        <%= "**** **** **** " + @default_card_information.last4 %>
      </div>

      <%# 有効期限 %>
      <div>
        有効期限
        <% exp_month = @default_card_information.exp_month.to_s %>
        <% exp_year = @default_card_information.exp_year.to_s.slice(2,3) %>
        <%= exp_month + " / " + exp_year %>
      </div>

      <%# 登録ボタン %>
      <%= form_with url:delete_cards_path, method: :post, id: 'charge-form', name: "inputForm", local: true do %>
        <input type="hidden" name="card_id" value="">
        <button class="btn btn-primary">削除する</button>
      <% end %>
  </div>
</div>