config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations:"registrations",sessions: :sessions }

  root "top#index"

  resources :posts, only: %i(new create index show destroy) do
    resources :arts, only: %i(create)
    resources :comments, only: %i(create destroy)
    collection do
      get 'search'
    end
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
   end

  resources :users, only:[:show,:index]
  resources :reactions, only: [:create]
  resources :matching, only: [:index]

  resources :chat_rooms, only: [:create, :show]

  get "/swipe", to: "posts#swipe"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  belongs_to :post

  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users
  has_many :chat_messages
  has_many :users, through: :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :arts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reactions, -> { order(created_at: :desc) }, dependent: :destroy

  accepts_nested_attributes_for :arts
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  has_many :chat_room_users, dependent: :destroy
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages, dependent: :destroy

  has_one :card, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,presence: true
  validates :self_introduction,length: { maximum: 500 }

  mount_uploader :profile_image, ProfileImageUploader

  def update_without_current_password(params, *options)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user
  before_action :set_q, only: [:index, :search]

  def new
    @post = Post.new
    @post.arts.build
  end

  def create
    @post = Post.new(post_params)
    if @post.arts.present?
      @post.save
      redirect_to posts_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to posts_path
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to posts_path
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comments = @post.comments
    @comment = @post.comments.build
  end

  def index
    @posts = Post.page(params[:page]).per(9).includes(:arts, :user).order('created_at DESC')
  end

  def swipe
    @posts = Post.where.not(user_id: current_user.id)
    @user = User.find(current_user.id)
  end

  def search
    @results = @q.result
  end

  private
    def post_params
      params.require(:post).permit(:art_text, arts_attributes: [:image]).merge(user_id: current_user.id)
    end

    def set_q
      @q = Post.ransack(params[:q])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(name, **options)
    Initials.svg(name, size: 40)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/index.html.erb
<%#　検索窓 %>
<div class="flex justify-center mb-5">
  <div class="form-control">
    <%= search_form_for @q, url: search_posts_path do |f| %>
      <%= f.search_field :art_text_cont, class: "input input-bordered", placeholder: "Search", type: "text" %>
      <%= f.submit '検索', class: "btn" %>
    <% end %>
  </div>
</div>
<div class="grid grid-cols-1 md:grid-cols-3">
  <% @posts.each do |post| %>
    <%# 投稿表示 %>
    <div class="card w-96 bg-base-100 shadow-xl">
      <%# 投稿画像 %>
      <%= link_to(post_path(post)) do %>
        <%= image_tag post.arts.first.image.url(:medium) %>
      <% end %>
      <%# 投稿情報 %>
      <div class="card-body">
        <%# 作品詳細 %>
        <%= post.art_text %>
        <div class="justify-end card-actions">
          <%# user詳細　%>
          <% post_user = User.find_by(id: post.user_id) %>
          <%# user name %>
          <%= post_user.name%>
          <%# user avatar %>
          <% if post_user.profile_image.url.nil? %>
            <label tabindex="0" class="btn btn-ghost btn-circle avatar">
              <div class="w-10 rounded-full">
                <%= user_avatar(post_user.name) %>
              </div>
            </label>
          <% else %>
            <label tabindex="0" class="btn btn-ghost btn-circle avatar">
              <div class="w-10 rounded-full">
                <%= image_tag post_user.profile_image.url, class: "profile-img" %>
              </div>
            </label>
          <% end %>
        </div>

      </div>
    </div>
  <% end %>
</div>
<div class="flex justify-center">
  <div>
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post do |f| %>
  <div class="flex justify-center">
    <div class="card flex-shrink-0 w-1/2 shadow-2xl bg-base-100 justify-center">
    
      <%# カード中身　%>
      <div class="card-body">
        <div class="text-center font-bold mb-5">
          作品を投稿する
        </div>

        <div class="form-control">
          <%= f.text_field :art_text %>
        </div>

        <div class="form-control">
          <%= f.fields_for :arts do |i| %>
            <%= i.file_field :image %>
          <% end %>
        </div>

        <div class="form-control">
          <%= f.submit "投稿", class: "btn btn-primary" %>
        </div>
      <div>

    </div>
  </div>
<% end %>

app/views/posts/search.html.erb
<h1 class="text-center font-bold">検索結果</h1>
<div class="grid grid-cols-1 md:grid-cols-3">
  <% @results.each do |post| %>
    <%# 投稿表示 %>
    <div class="card w-96 bg-base-100 shadow-xl">
      <%# 投稿画像 %>
      <%= link_to(post_path(post)) do %>
        <%= image_tag post.arts.first.image.url(:medium) %>
      <% end %>
      <%# 投稿情報 %>
      <div class="card-body">
        <%# 作品詳細 %>
        <%= post.art_text %>
        <div class="justify-end card-actions">
          <%# user詳細　%>
          <% post_user = User.find_by(id: post.user_id) %>
          <%# user name %>
          <%= post_user.name%>
          <%# user avatar %>
          <% if post_user.profile_image.url.nil? %>
            <label tabindex="0" class="btn btn-ghost btn-circle avatar">
              <div class="w-10 rounded-full">
                <%= user_avatar(post_user.name) %>
              </div>
            </label>
          <% else %>
            <label tabindex="0" class="btn btn-ghost btn-circle avatar">
              <div class="w-10 rounded-full">
                <%= image_tag post_user.profile_image.url, class: "profile-img" %>
              </div>
            </label>
          <% end %>
        </div>

      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%# 投稿表示 %>
<div class="card w-96 bg-base-100 shadow-xl mx-auto">
  <%# 投稿画像 %>
  <%= image_tag @post.arts.first.image.url(:medium) %>
  <%# 投稿情報 %>
  <div class="card-body">
    <%# 作品詳細 %>
    <%= @post.art_text %>
    <%# 削除ボタン %>
    <% if @post.user_id == current_user.id %>
      <div class="card-actions">
        <%= button_to "削除", post_path(@post), method: :delete, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <%# コメント　%>
  <%# コメント一覧　%>
  <h2 class="mx-auto">コメント一覧</h2>
  <div class="overflow-x-auto w-full">
    <table class="table w-full">
    <%# コメントテーブル　%>
    <% @comments.each do |comment| %>
    <% comment_user = User.find_by(id: comment.user_id) %>
      <tr>
        <td>
        </td>
        <td>
          <%= comment.comment %>
        </td>
      </tr>
    <% end %>
    </table>
  </div>

    <%# コメント投稿　%>
    <div class="flex justify-center">
      <%= form_with(model: [@post, @comment], local: true, method: :post) do |f| %>
        <%= f.text_field :comment, class: "textarea textarea-primary" %>
        <br>
        <div class="text-center">
          <%= f.submit 'コメントする', class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/posts/swipe.html.erb
<div class="user-index-page">

  <div class="swipe flex justify-center flex-col">
    <div class="swipe--status">
    </div>

    <%# 重ね合わせたカード %>
    <div class="swipe--cards stack mt-5 mb-5">
      <% @posts.each do |post| %>
        <div class="swipe--card grid card w-96 bg-base-100 shadow-xl" id="<%= post.id %>">
          <%= image_tag post.arts.first.image.url(:medium), class:"profile-img" %>
          <%# 投稿情報 %>
          <div class="card-body">
            <%# 作品詳細 %>
            <%= post.art_text %>
            <div class="justify-end card-actions">
              <%# user詳細　%>
              <% post_user = User.find_by(id: post.user_id) %>
              <%# user name %>
              <%= post_user.name%>
              <%# user avatar %>
              <% if post_user.profile_image.url.nil? %>
                <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                  <div class="w-10 rounded-full">
                    <%= user_avatar(post_user.name) %>
                  </div>
                </label>
              <% else %>
                <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                  <div class="w-10 rounded-full">
                    <%= image_tag post_user.profile_image.url, class: "profile-img" %>
                  </div>
                </label>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="swipe--buttons mx-auto mb-5">
      <button id="dislike" class="btn btn-secondary">dislike</button>
      <button id="like" class="btn btn-primary">like</button>
    </div>
  </div>

</div>